name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */4 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "huixiongyu@gmail.com"
          git config --local user.name "huixiongyu"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Stay hungry, stay foolish!"
          git push
